version: '3'

services:
  app:
    image: localhost:5000/sorteio3
    env_file: .env
    environment:
      REDIS_HOST: redis
    depends_on:
      - redis
    build: .
    ports:
      - "8181:8080"
    networks:
      - network1
  redis:
    image: redis
    command: ['redis-server', '--appendonly', 'yes']
    ports:
      - "6379:6379"
    networks:
      - network1
    volumes:
      - ./redis:/data

networks:
  network1:
    driver: bridge
